import React, { useMemo } from 'react';
import { Sprout } from 'lucide-react';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import SourceCard from './SourceCard';

/**
 * Parses assistant response text to extract any trailing source section
 */
function parseMessageContent(text) {
  if (!text) return { body: '', sources: null };

  // Match common source patterns generated by Gemini / RAG:
  // e.g. "*(Source: Fertilizer & Nutrient Management, pages 1, 2, 4, 8)*",
  // "Source: ...", "**Source:** ...", "(Sources: ...)"
  const sourceRegex = /(?:(?:\r?\n)+)(?:[\*\_\(\[\{]{0,3}\s*(?:Sources?|References?|Source Note):?\s*)([\s\S]*)$/i;
  const match = text.match(sourceRegex);

  if (match && match.index !== undefined) {
    const body = text.substring(0, match.index).trim();
    let rawSources = match[1].trim();
    // Clean trailing closing parens, asterisks, brackets from markdown formatting
    rawSources = rawSources.replace(/[\)\*\_\]\}\s]+$/, '').trim();

    if (body.length > 0 && rawSources.length > 0) {
      return { body, sources: rawSources };
    }
  }

  return { body: text, sources: null };
}

export default function ChatMessage({ message }) {
  const isUser = message.role === 'user';

  const { body, sources } = useMemo(() => {
    if (isUser) {
      return { body: message.text, sources: null };
    }
    return parseMessageContent(message.text);
  }, [isUser, message.text]);

  return (
    <div className={`message-row ${isUser ? 'user' : 'assistant'}`}>
      {!isUser && (
        <div className="assistant-avatar" aria-hidden="true" title="AgriGuide Assistant">
          <Sprout size={18} strokeWidth={2.4} />
        </div>
      )}

      <div className="message-bubble">
        {isUser ? (
          <p className="user-message-text" style={{ whiteSpace: 'pre-wrap', margin: 0 }}>{body}</p>
        ) : (
          <>
            <div className="assistant-bubble-header">
              <span className="assistant-name">AgriGuide AI</span>
              <span className="assistant-role-tag">Agriculture Advisory</span>
            </div>
            <div className="markdown-body">
              <Markdown remarkPlugins={[remarkGfm]}>
                {body}
              </Markdown>
            </div>
            {sources && <SourceCard sourceContent={sources} />}
          </>
        )}
      </div>
    </div>
  );
}
